/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package com.wdyapplications.e_commerce_api.utils.enums;

/**
 * 
 * @author Dorgeddy
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// ADDRESSES
	VIEW_ADDRESSES("VIEW_ADDRESSES"),	
	CREATE_ADDRESSES("CREATE_ADDRESSES"),
	UPDATE_ADDRESSES("UPDATE_ADDRESSES"),
	DELETE_ADDRESSES("DELETE_ADDRESSES"),
	// ADMIN_STATS
	VIEW_ADMIN_STATS("VIEW_ADMIN_STATS"),	
	CREATE_ADMIN_STATS("CREATE_ADMIN_STATS"),
	UPDATE_ADMIN_STATS("UPDATE_ADMIN_STATS"),
	DELETE_ADMIN_STATS("DELETE_ADMIN_STATS"),
	// CART_ITEMS
	VIEW_CART_ITEMS("VIEW_CART_ITEMS"),	
	CREATE_CART_ITEMS("CREATE_CART_ITEMS"),
	UPDATE_CART_ITEMS("UPDATE_CART_ITEMS"),
	DELETE_CART_ITEMS("DELETE_CART_ITEMS"),
	// CARTS
	VIEW_CARTS("VIEW_CARTS"),	
	CREATE_CARTS("CREATE_CARTS"),
	UPDATE_CARTS("UPDATE_CARTS"),
	DELETE_CARTS("DELETE_CARTS"),
	// CATEGORIES
	VIEW_CATEGORIES("VIEW_CATEGORIES"),	
	CREATE_CATEGORIES("CREATE_CATEGORIES"),
	UPDATE_CATEGORIES("UPDATE_CATEGORIES"),
	DELETE_CATEGORIES("DELETE_CATEGORIES"),
	// CONVERSATIONS
	VIEW_CONVERSATIONS("VIEW_CONVERSATIONS"),	
	CREATE_CONVERSATIONS("CREATE_CONVERSATIONS"),
	UPDATE_CONVERSATIONS("UPDATE_CONVERSATIONS"),
	DELETE_CONVERSATIONS("DELETE_CONVERSATIONS"),
	// MESSAGES
	VIEW_MESSAGES("VIEW_MESSAGES"),	
	CREATE_MESSAGES("CREATE_MESSAGES"),
	UPDATE_MESSAGES("UPDATE_MESSAGES"),
	DELETE_MESSAGES("DELETE_MESSAGES"),
	// NOTIFICATIONS
	VIEW_NOTIFICATIONS("VIEW_NOTIFICATIONS"),	
	CREATE_NOTIFICATIONS("CREATE_NOTIFICATIONS"),
	UPDATE_NOTIFICATIONS("UPDATE_NOTIFICATIONS"),
	DELETE_NOTIFICATIONS("DELETE_NOTIFICATIONS"),
	// ORDER_ITEMS
	VIEW_ORDER_ITEMS("VIEW_ORDER_ITEMS"),	
	CREATE_ORDER_ITEMS("CREATE_ORDER_ITEMS"),
	UPDATE_ORDER_ITEMS("UPDATE_ORDER_ITEMS"),
	DELETE_ORDER_ITEMS("DELETE_ORDER_ITEMS"),
	// ORDERS
	VIEW_ORDERS("VIEW_ORDERS"),	
	CREATE_ORDERS("CREATE_ORDERS"),
	UPDATE_ORDERS("UPDATE_ORDERS"),
	DELETE_ORDERS("DELETE_ORDERS"),
	// PAYMENTS
	VIEW_PAYMENTS("VIEW_PAYMENTS"),	
	CREATE_PAYMENTS("CREATE_PAYMENTS"),
	UPDATE_PAYMENTS("UPDATE_PAYMENTS"),
	DELETE_PAYMENTS("DELETE_PAYMENTS"),
	// PRODUCT_IMAGES
	VIEW_PRODUCT_IMAGES("VIEW_PRODUCT_IMAGES"),	
	CREATE_PRODUCT_IMAGES("CREATE_PRODUCT_IMAGES"),
	UPDATE_PRODUCT_IMAGES("UPDATE_PRODUCT_IMAGES"),
	DELETE_PRODUCT_IMAGES("DELETE_PRODUCT_IMAGES"),
	// PRODUCTS
	VIEW_PRODUCTS("VIEW_PRODUCTS"),	
	CREATE_PRODUCTS("CREATE_PRODUCTS"),
	UPDATE_PRODUCTS("UPDATE_PRODUCTS"),
	DELETE_PRODUCTS("DELETE_PRODUCTS"),
	// PROMOTION_PRODUCTS
	VIEW_PROMOTION_PRODUCTS("VIEW_PROMOTION_PRODUCTS"),	
	CREATE_PROMOTION_PRODUCTS("CREATE_PROMOTION_PRODUCTS"),
	UPDATE_PROMOTION_PRODUCTS("UPDATE_PROMOTION_PRODUCTS"),
	DELETE_PROMOTION_PRODUCTS("DELETE_PROMOTION_PRODUCTS"),
	// PROMOTION_USAGE
	VIEW_PROMOTION_USAGE("VIEW_PROMOTION_USAGE"),	
	CREATE_PROMOTION_USAGE("CREATE_PROMOTION_USAGE"),
	UPDATE_PROMOTION_USAGE("UPDATE_PROMOTION_USAGE"),
	DELETE_PROMOTION_USAGE("DELETE_PROMOTION_USAGE"),
	// PROMOTIONS
	VIEW_PROMOTIONS("VIEW_PROMOTIONS"),	
	CREATE_PROMOTIONS("CREATE_PROMOTIONS"),
	UPDATE_PROMOTIONS("UPDATE_PROMOTIONS"),
	DELETE_PROMOTIONS("DELETE_PROMOTIONS"),
	// REVIEWS
	VIEW_REVIEWS("VIEW_REVIEWS"),	
	CREATE_REVIEWS("CREATE_REVIEWS"),
	UPDATE_REVIEWS("UPDATE_REVIEWS"),
	DELETE_REVIEWS("DELETE_REVIEWS"),
	// SELLER_STATS
	VIEW_SELLER_STATS("VIEW_SELLER_STATS"),	
	CREATE_SELLER_STATS("CREATE_SELLER_STATS"),
	UPDATE_SELLER_STATS("UPDATE_SELLER_STATS"),
	DELETE_SELLER_STATS("DELETE_SELLER_STATS"),
	// SESSIONS
	VIEW_SESSIONS("VIEW_SESSIONS"),	
	CREATE_SESSIONS("CREATE_SESSIONS"),
	UPDATE_SESSIONS("UPDATE_SESSIONS"),
	DELETE_SESSIONS("DELETE_SESSIONS"),
	// STOCK_HISTORY
	VIEW_STOCK_HISTORY("VIEW_STOCK_HISTORY"),	
	CREATE_STOCK_HISTORY("CREATE_STOCK_HISTORY"),
	UPDATE_STOCK_HISTORY("UPDATE_STOCK_HISTORY"),
	DELETE_STOCK_HISTORY("DELETE_STOCK_HISTORY"),
	// USERS
	VIEW_USERS("VIEW_USERS"),	
	CREATE_USERS("CREATE_USERS"),
	UPDATE_USERS("UPDATE_USERS"),
	DELETE_USERS("DELETE_USERS");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
