/*
 * Created on 2025-08-23 ( Time 06:18:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "admin_stats"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="admin_stats" )
public class AdminStats implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="stats_date", nullable=false)
    private Date       statsDate    ;

    @Column(name="total_revenue")
    private BigDecimal totalRevenue ;

    @Column(name="total_orders")
    private Integer    totalOrders  ;

    @Column(name="active_users")
    private Integer    activeUsers  ;

    @Column(name="new_users")
    private Integer    newUsers     ;

    @Column(name="total_products")
    private Integer    totalProducts ;

    @Column(name="out_of_stock_products")
    private Integer    outOfStockProducts ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="calculated_at")
    private Date       calculatedAt ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AdminStats() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
