/*
 * Created on 2025-08-23 ( Time 06:18:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "cart_items"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="cart_items" )
public class CartItems implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="quantity", nullable=false)
    private Integer    quantity     ;

    @Column(name="unit_price", nullable=false)
    private BigDecimal unitPrice    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="added_at")
    private Date       addedAt      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

	// "cartId" (column "cart_id") is not defined by itself because used as FK in a link 
	// "productId" (column "product_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id")
    private Products products    ;
    @ManyToOne
    @JoinColumn(name="cart_id", referencedColumnName="id")
    private Carts carts       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CartItems() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
