/*
 * Created on 2025-08-23 ( Time 06:18:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "messages"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="messages" )
public class Messages implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="content", length=2147483647)
    private String     content      ;

    @Column(name="type", length=2147483647)
    private String     type         ;

    @Column(name="attachment_url", length=500)
    private String     attachmentUrl ;

    @Column(name="is_read")
    private Boolean    isRead       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="read_at")
    private Date       readAt       ;

	// "conversationId" (column "conversation_id") is not defined by itself because used as FK in a link 
	// "senderId" (column "sender_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="sender_id", referencedColumnName="id")
    private Users users       ;
    @ManyToOne
    @JoinColumn(name="conversation_id", referencedColumnName="id")
    private Conversations conversations;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Messages() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
