/*
 * Created on 2025-08-23 ( Time 06:18:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "orders"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="orders" )
public class Orders implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="order_number", nullable=false, length=50)
    private String     orderNumber  ;

    @Column(name="status", length=2147483647)
    private String     status       ;

    @Column(name="subtotal", nullable=false)
    private BigDecimal subtotal     ;

    @Column(name="tax_amount")
    private BigDecimal taxAmount    ;

    @Column(name="shipping_cost")
    private BigDecimal shippingCost ;

    @Column(name="discount_amount")
    private BigDecimal discountAmount ;

    @Column(name="total_amount", nullable=false)
    private BigDecimal totalAmount  ;

    @Column(name="shipping_address", nullable=false, length=2147483647)
    private String     shippingAddress ;

    @Column(name="billing_address", length=2147483647)
    private String     billingAddress ;

    @Column(name="payment_method", length=50)
    private String     paymentMethod ;

    @Column(name="payment_status", length=50)
    private String     paymentStatus ;

    @Column(name="tracking_number", length=100)
    private String     trackingNumber ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="shipped_at")
    private Date       shippedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="delivered_at")
    private Date       deliveredAt  ;

	// "customerId" (column "customer_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="customer_id", referencedColumnName="id")
    private Users users       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Orders() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
