/*
 * Created on 2025-08-23 ( Time 06:18:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "products"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="products" )
public class Products implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", nullable=false, length=255)
    private String     name         ;

    @Column(name="description", length=2147483647)
    private String     description  ;

    @Column(name="price", nullable=false)
    private BigDecimal price        ;

    @Column(name="promo_price")
    private BigDecimal promoPrice   ;

    @Column(name="stock_quantity")
    private Integer    stockQuantity ;

    @Column(name="min_stock_alert")
    private Integer    minStockAlert ;

    @Column(name="status", length=2147483647)
    private String     status       ;

    @Column(name="average_rating")
    private BigDecimal averageRating ;

    @Column(name="total_reviews")
    private Integer    totalReviews ;

    @Column(name="total_sales")
    private Integer    totalSales   ;

    @Column(name="is_featured")
    private Boolean    isFeatured   ;

    @Column(name="is_recommended")
    private Boolean    isRecommended ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

	// "sellerId" (column "seller_id") is not defined by itself because used as FK in a link 
	// "categoryId" (column "category_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="category_id", referencedColumnName="id")
    private Categories categories  ;
    @ManyToOne
    @JoinColumn(name="seller_id", referencedColumnName="id")
    private Users users       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Products() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
