/*
 * Created on 2025-08-23 ( Time 06:18:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "promotions"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="promotions" )
public class Promotions implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="code", nullable=false, length=50)
    private String     code         ;

    @Column(name="name", nullable=false, length=255)
    private String     name         ;

    @Column(name="description", length=2147483647)
    private String     description  ;

    @Column(name="type", nullable=false, length=2147483647)
    private String     type         ;

    @Column(name="value", nullable=false)
    private BigDecimal value        ;

    @Column(name="min_order_amount")
    private BigDecimal minOrderAmount ;

    @Column(name="max_uses")
    private Integer    maxUses      ;

    @Column(name="used_count")
    private Integer    usedCount    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false)
    private Date       startDate    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", nullable=false)
    private Date       endDate      ;

    @Column(name="is_active")
    private Boolean    isActive     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Promotions() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
