/*
 * Created on 2025-08-23 ( Time 06:18:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "promotion_usage"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="promotion_usage" )
public class PromotionUsage implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="discount_amount", nullable=false)
    private BigDecimal discountAmount ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="used_at")
    private Date       usedAt       ;

	// "promotionId" (column "promotion_id") is not defined by itself because used as FK in a link 
	// "orderId" (column "order_id") is not defined by itself because used as FK in a link 
	// "userId" (column "user_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="id")
    private Orders orders      ;
    @ManyToOne
    @JoinColumn(name="promotion_id", referencedColumnName="id")
    private Promotions promotions  ;
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id")
    private Users users       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PromotionUsage() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
