/*
 * Created on 2025-08-23 ( Time 06:18:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "promotion_products"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="promotion_products" )
public class PromotionProducts implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

	// "promotionId" (column "promotion_id") is not defined by itself because used as FK in a link 
	// "productId" (column "product_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id")
    private Products products    ;
    @ManyToOne
    @JoinColumn(name="promotion_id", referencedColumnName="id")
    private Promotions promotions  ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PromotionProducts() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
