/*
 * Created on 2025-08-23 ( Time 06:18:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "seller_stats"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="seller_stats" )
public class SellerStats implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="year", nullable=false)
    private Integer    year         ;

    @Column(name="month", nullable=false)
    private Integer    month        ;

    @Column(name="total_revenue")
    private BigDecimal totalRevenue ;

    @Column(name="total_orders")
    private Integer    totalOrders  ;

    @Column(name="total_products_sold")
    private Integer    totalProductsSold ;

    @Column(name="average_rating")
    private BigDecimal averageRating ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="calculated_at")
    private Date       calculatedAt ;

	// "sellerId" (column "seller_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="seller_id", referencedColumnName="id")
    private Users users       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SellerStats() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
