/*
 * Created on 2025-08-23 ( Time 06:18:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "stock_history"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="stock_history" )
public class StockHistory implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    // test value Integer
        private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="old_quantity", nullable=false)
    private Integer    oldQuantity  ;

    @Column(name="new_quantity", nullable=false)
    private Integer    newQuantity  ;

    @Column(name="change_quantity", nullable=false)
    private Integer    changeQuantity ;

    @Column(name="reason", nullable=false, length=2147483647)
    private String     reason       ;

    @Column(name="reference_id", length=100)
    private String     referenceId  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

	// "productId" (column "product_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id")
    private Products products    ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StockHistory() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
