/*
 * Created on 2025-08-27 ( Time 18:33:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wdyapplications.e_commerce_api.dao.entity;

import java.io.Serializable;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

//import jakarta.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import jakarta.persistence.*;

/**
 * Persistent class for entity stored in table "users"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name="users" )
public class Users implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="email", nullable=false, length=255)
    private String     email        ;

    @Column(name="password_hash", nullable=false, length=255)
    private String     passwordHash ;

    @Column(name="first_name", nullable=false, length=100)
    private String     firstName    ;

    @Column(name="last_name", nullable=false, length=100)
    private String     lastName     ;

    @Column(name="phone", length=20)
    private String     phone        ;

    @Column(name="avatar_url", length=500)
    private String     avatarUrl    ;

    @Column(name="role", length=2147483647)
    private String     role         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login")
    private Date       lastLogin    ;

    @Column(name="is_active")
    private Boolean    isActive     ;

    @Column(name="reset_token", length=255)
    private String     resetToken   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="reset_token_expires")
    private Date       resetTokenExpires ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Users() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
